api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "fulfillment-constraints"
type = "function"
uid = "32d3f4bd-4327-2bf2-c594-85c8cf923852bb22db08"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.fulfillment-constraints.generate.run"
  input_query = "src/cart_fulfillment_constraints_generate_run.graphql"
  export = "cart-fulfillment-constraints-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
