# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b06c909488528dc7a8d9f1b83c055ae"
name = "hatley-b2b"
application_url = "https://zealand-reads-nelson-nevada.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/webhooks/app/uninstalled"

# Subscribe to order creation events
[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"

[access_scopes]
scopes = "read_fulfillments,write_fulfillments,write_fulfillment_constraint_rules,read_products,write_products,read_orders,write_orders,read_locations,read_companies,write_companies,write_customers,read_customers,read_inventory,customer_read_companies,customer_write_companies,customer_read_locations,customer_write_locations"


use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://zealand-reads-nelson-nevada.trycloudflare.com/auth/callback",
  "https://zealand-reads-nelson-nevada.trycloudflare.com/auth/shopify/callback",
  "https://zealand-reads-nelson-nevada.trycloudflare.com/api/auth/callback"
]
